### ISSUE TITLE
Typrerror when running joint-Model_test.py

### ISSUE THREAD

**Issue by HeJunhong1107** [Shen-Lab/DeepAffinity#16]
I'm trying to use deep affinity with pretained error, but the error appeared :

Tokenizing data in ./data/test_sps
Tokenizing data in ./data/test_smile
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 577, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("GRU/GRU/GRUCell/Gates/add:0", shape=(64, 512), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "joint-Model_test.py", line 230, in <module>
    prot_gru_1 = tflearn.gru(prot_embd, GRU_size_prot,initial_state= prot_init_state_1,trainable=True,return_seq=True,restore=True)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 294, in gru
    scope=scope, name=name)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 67, in _rnn_template
    sequence_length=sequence_length)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 197, in static_rnn
    (output, state) = call_cell()
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 184, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tflearn/layers/recurrent.py", line 601, in __call__
    self.trainable, self.restore, self.reuse))
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1198, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3306, in _split
    num_split=num_split, name=name)
  File "/home/recher/anaconda3/envs/deep_affinity/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 514, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by HeJunhong1107** [comment]
here were my environment：
Package         Version
--------------- -----------
cached-property 1.5.2
certifi         2021.5.30
dataclasses     0.8
h5py            3.1.0
numpy           1.19.5
pandas          1.1.5
patsy           0.5.6
Pillow          8.4.0
pip             21.2.2
protobuf        3.19.6
python-dateutil 2.9.0.post0
pytz            2024.1
scikit-learn    0.19.0
scipy           1.5.4
setuptools      58.0.4
six             1.16.0
statsmodels     0.12.2
tensorflow-gpu  1.1.0
tflearn         0.3
Werkzeug        2.0.3
wheel           0.37.1

**Comment by HeJunhong1107** [comment]
here were my environment：
![屏幕截图 2024-04-22 202110](https://github.com/Shen-Lab/DeepAffinity/assets/126778402/fa121135-fc7f-4b4b-9b32-64c364d2d4ae)
