### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by vijec** [Shen-Lab/DeepAffinity#2]
Hi, 

Is it possible to share the trained models?

Thanks.

**Comment by AstroSign** [comment]
Hi ecvgit,

Sorry for late reply. We just uploaded the checkpoints of trained model for warm start joint attention model, which is under directory: DeepAffinity/Joint_models/joint_attention/joint_warm_start/.

The checkpoints files that is trained based on the whole IC50 dataset are uploaded to Google Drive and you can find them at here: [checkpoints](https://drive.google.com/drive/folders/1XAnXHSRnrO8DGA1drW3YnmaBaCihdiP5?usp=sharing)

In addition, we updated our README. You can find model checkpoints that are trained based on training set of IC50 dataset and more related information there.

If you would like to test novel proteins, please refer to the transfer learning method in our paper.

Thanks.

**Comment by Shen-Lab** [comment]
I would like to add that the link provided above is for 3 checkpoints (3 models) trained over a training set without any GPCR, ion channel, estrogen receptor, or tyrosine kinase receptor.  This was done so that the models could be later assessed and transferred for these 4 new classes.  

We also provided a link in the updated README to a checkpoint for a new model trained over all data we curated from BindingDB.  This model might be a better one for your application needs.  Also, if you are interested in a specific class of protein targets, it would be better to fine-tune the aforementioned "generic" model using the transfer learning technologies we described in the paper.  We have shown that the performance can be drastically boosted using as few as dozens of labeled protein-ligand pairs for the protein class of interest.

**Comment by vijec** [comment]
Thank you.

**Comment by vijec** [comment]
Hi - It seems like there is a version mismatch. I get the following error. 

  File "joint-Model_test.py", line 25, in <module>
    from recurrent import bidirectional_rnn, BasicLSTMCell,GRUCell
ModuleNotFoundError: No module named 'recurrent'

I fixed it by uncommenting the previous line 
#from tflearn.layers.recurrent import bidirectional_rnn, BasicLSTMCell,GRUCell

However, there was another error.

Traceback (most recent call last):
  File "joint-Model_test.py", line 216, in <module>
    test_IC50 = read_labels("./data/test_ic50")
  File "joint-Model_test.py", line 154, in read_labels
    return y
NameError: name 'y' is not defined

I fixed it by changing y to x.

Then, I get another error.

Traceback (most recent call last):
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key Attn not found in checkpoint
         [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "joint-Model_test.py", line 282, in <module>
    model.load('checkpoints-'+str(checkpoints))
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tflearn-0.3.2-py3.6.egg/tflearn/models/dnn.py", line 308, in load
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tflearn-0.3.2-py3.6.egg/tflearn/helpers/trainer.py", line 490, in restore
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Attn not found in checkpoint
         [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

Caused by op 'save_1/RestoreV2_3', defined at:
  File "joint-Model_test.py", line 279, in <module>
    model = tflearn.DNN(reg, tensorboard_verbose=0,tensorboard_dir='./mytensor/',checkpoint_path="./checkpoints/")
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tflearn-0.3.2-py3.6.egg/tflearn/models/dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tflearn-0.3.2-py3.6.egg/tflearn/helpers/trainer.py", line 147, in __init__
    allow_empty=True)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/speech7/multimodal/work/inkpad/miniconda3/envs/py3o6_tf1o1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key Attn not found in checkpoint
         [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

Is it possible to share a requirements.txt or environment.yml file so that I have the right dependencies installed? May be test it using a fresh conda environment.

Thank you very much again for your quick responses.

**Comment by vijec** [comment]
This is my environment

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl    anaconda
ca-certificates           2019.8.28                     0    anaconda
certifi                   2019.9.11                py36_0    anaconda
cudatoolkit               7.5                           2    anaconda
cudnn                     5.1                           0    anaconda
freetype                  2.9.1                h8a8886c_1  
h5py                      2.9.0            py36h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
intel-openmp              2019.5                      281    anaconda
jpeg                      9b                   h024ee3a_2  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.9.2                hd408876_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
mkl                       2019.5                      281    anaconda
mkl-service               2.3.0            py36he904b0f_0    anaconda
ncurses                   6.1                  he6710b0_1  
numpy                     1.11.3           py36hcd700cb_6    anaconda
numpy-base                1.17.2           py36hde5b4d6_0    anaconda
olefile                   0.46                     py36_0  
openssl                   1.1.1                h7b6447c_0    anaconda
pandas                    0.22.0           py36hf484d3e_0    anaconda
patsy                     0.5.1                    py36_0    anaconda
pillow                    6.2.0            py36h34e0f95_0  
pip                       19.2.3                   py36_0  
protobuf                  3.9.2            py36he6710b0_0    anaconda
python                    3.6.9                h265db76_0  
python-dateutil           2.8.0                    py36_0    anaconda
pytz                      2019.3                     py_0    anaconda
readline                  7.0                  h7b6447c_5  
scikit-learn              0.19.2           py36h4989274_0    anaconda
scipy                     1.3.1            py36h7c811a0_0    anaconda
setuptools                41.4.0                   py36_0  
six                       1.12.0                   py36_0    anaconda
sqlite                    3.30.0               h7b6447c_0  
statsmodels               0.10.1           py36hdd07704_0    anaconda
tensorflow                1.1.0               np111py36_0    anaconda
tensorflow-gpu            1.1.0               np111py36_0    anaconda
tflearn                   0.3.2            py36he51c03d_0    contango
tk                        8.6.8                hbc83047_0  
werkzeug                  0.16.0                     py_0    anaconda
wheel                     0.33.6                   py36_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0

**Comment by AstroSign** [comment]
Hi ecvgit,

Sorry for late reply. We have corrected those errors in code and provided our environment as environment.yml. Also we have tested the checkpoint we provided on our super computer. Could you please try to create your conda environment by the .yml file we provided and test again?

If you encounter any problem again, please feel free to contact us.

Thanks.

**Comment by AstroSign** [comment]
Hi ecvgit,

Sorry for late reply. Thanks for your remind and we have fixed thsoe two bugs in our code. In addition, we also updated our README and provided environment.yml under the root directory. Also, we tested on our computer and updated the checkpoint based on training set. Please download it again and try to run the testing program with the new checkpoint.

If you have any further question, please feel free to contact us.

Thanks.
